import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BiUserPlus} from 'react-icons/bi';
import Table from '../Components/table';
import Form from '../Components/form';
import { useState } from 'react';
export default function Home() {

  const[visible,setVisible]=useState(false)

const handler=()=>{
setVisible(!visible)
}

  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
     <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Customer Details</h1>
     <div className='container mx-auto flex justify-between py-5 border-b'>
<div className='left flex gap-3'>
<button onClick={handler} className='flex bg-orange-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-orange-500 hover text-gray-800'>
  Add Customer <BiUserPlus size={23}/>
</button>
</div>
     </div>

{visible?<Form/> :<></>}
   
     <div className='container mx-auto'>
     <Table/>
     </div>
      </main>
    </section>
  )
}
